### ISSUE TITLE
CentOS 无法启动流媒体服务？失败  

### ISSUE THREAD

**Issue by eternityzqf** [tsingsee/EasyDSS-Kernel#2]
按照Github 文档  使用Centos 服务器 启动流媒体服务失败 求解.感谢指导。
![微信截图_20190827145138](https://user-images.githubusercontent.com/16233519/63747863-aea53880-c8da-11e9-95ea-790c97fe1dea.png)

**Comment by babosa** [comment]
logs/目录里面的log文件，帮忙打开看看里面是怎么提示的

**Comment by eternityzqf** [comment]
------------------ 原始邮件 ------------------
发件人: "Babosa"<notifications@github.com>;
发送时间: 2019年8月30日(星期五) 中午1:52
收件人: "tsingsee/EasyDSS-Kernel"<EasyDSS-Kernel@noreply.github.com>;
抄送: "qwer"<1583510917@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [tsingsee/EasyDSS-Kernel] CentOS 无法启动流媒体服务？失败   (#2)




logs/目录里面的log文件，帮忙打开看看里面是怎么提示的

**Comment by gavin1010** [comment]
看表面现象，是启动完成了，进程在后台运行，是没有界面的，要通过http://serverip:port访问

**Comment by eternityzqf** [comment]
请问这种默认设置的推流地址是：URL+默认端口（10085）？ 可是我用Windows版本默认设置推流能成功， Centos系统下默认设置下推流失败。求解。感谢。




------------------ 原始邮件 ------------------
发件人: "gavin1010"<notifications@github.com>;
发送时间: 2019年8月30日(星期五) 下午3:17
收件人: "tsingsee/EasyDSS-Kernel"<EasyDSS-Kernel@noreply.github.com>;
抄送: "qwer"<1583510917@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [tsingsee/EasyDSS-Kernel] CentOS 无法启动流媒体服务？失败   (#2)




看表面现象，是启动完成了，进程在后台运行，是没有界面的，要通过http://serverip:port访问

**Comment by babosa** [comment]
网页后台地址：http://ip:10088/可以看到服务是否启动成功；
推流地址默认是：rtmp://ip:10085/hls/{id}，id可以自己定义；

**Comment by eternityzqf** [comment]
非常感谢tsingsee的耐心解答；我尝试clone了最新的工程 重新配置启动成功了；也许是可能存在缺少配置，thank very much！
